name: Chaining jobs

on:
  workflow_dispatch: #manually run workflow
    inputs:
      run-job-3:
        description: 'Run job 3'
        required: true
        default: 'false'
        type: boolean

jobs:
  job-1:
    name: Job 1
    runs-on: ubuntu-latest
    steps:
      - name: Output for Job 1
        run: echo "This is Job 1. Run Job 3 equals ${{ github.event.inputs.run-job-3 }}"
  job-2:
    name: Job 2
    runs-on: ubuntu-latest
    needs: job-1 # Needs job 1 to complete successfully before it runs
    steps:
      - name: Output for Job 2
        run: echo "This is Job 2. Run Job 3 equals ${{ github.event.inputs.run-job-3 }}"
  job-3:
    name: Job 3
    if: github.event.inputs.run-job-3 == 'true' # Only run if the input is true
    runs-on: ubuntu-latest
    needs:
      - job-1
    steps:
      - name: Output for Job 3
        run: echo "This is Job 3. Run Job 3 equals ${{ github.event.inputs.run-job-3 }}"
  job-4:
    name: Job 4
    runs-on: ubuntu-latest
    needs:
      - job-2
      - job-3
    steps:
      - name: Output for Job 4
        run: echo "This is Job 4. Run Job 3 equals ${{ github.event.inputs.run-job-3 }}"
