name: Variables and Context

on:
  workflow_dispatch:
    inputs:
      name:
        default: Arianna
        required: true
        type: string

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Dump context
        env: # Environment variables local to this step
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"